const business = [
  {
    "article_id": "cac15c57070e13719b61bc7ce6a4c033",
    "title": "Tesla’s $56 Billion Pay Package For Elon Musk Opposed By Calpers CEO",
    "link": "https://www.ndtvprofit.com/business/tesla-s-56-billion-pay-package-for-musk-opposed-by-calpers-ceo",
    "keywords": ["business", "world", "bloomberg"],
    "creator": ["Chester Dawson"],
    "video_url": null,
    "description": "Calpers, the largest state public pension fund in the US, tentatively plans to vote against a proposed $56 billion pay package for Tesla Inc. Chief Executive Officer Elon Musk, a sign of opposition from a major investor.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-30 01:06:50",
    "image_url": "https://media.assettype.com/bloombergquint/2024-05/c582b594-ea98-4313-823e-af15bf21807a/_1x_1.jpg",
    "source_id": "bloombergquint",
    "source_priority": 9222807,
    "source_url": "https://www.bloombergquint.com",
    "source_icon": "https://i.bytvi.com/domain_icons/bloombergquint.png",
    "language": "english",
    "country": ["india"],
    "category": ["business"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "420571e00cdf6d005a0bb7304c9b793d",
    "title": "Apple Signals That It’s Working on TV+ App for Android Phones",
    "link": "https://www.ndtvprofit.com/technology/apple-signals-that-it-s-working-on-tv-app-for-android-phones",
    "keywords": ["technology", "bloomberg"],
    "creator": ["Mark Gurman"],
    "video_url": null,
    "description": "Apple Inc. is seeking a senior engineer to help build a television and sports app for Android, a sign the company is finally bringing its TV+ service to the rival smartphone platform.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-30 01:05:33",
    "image_url": "https://media.assettype.com/bloombergquint/2024-05/fafc28d8-5f83-4f6c-aa2a-dfaee482092b/_1x_1.jpg",
    "source_id": "bloombergquint",
    "source_priority": 9222807,
    "source_url": "https://www.bloombergquint.com",
    "source_icon": "https://i.bytvi.com/domain_icons/bloombergquint.png",
    "language": "english",
    "country": ["india"],
    "category": ["business"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "45f2f54511b3fe06379f3c1896536eec",
    "title": "FBI Takes Down Massive Global Army Of Zombie Computer Devices",
    "link": "https://www.ndtvprofit.com/world/fbi-takes-down-massive-global-army-of-zombie-computer-devices",
    "keywords": ["world", "technology", "bloomberg"],
    "creator": ["Katrina Manson"],
    "video_url": null,
    "description": "The FBI said it has dismantled what is likely the world’s largest botnet — an army of 19 million infected computers — that was leased to hackers for cybercrimes.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-30 01:03:57",
    "image_url": "https://media.assettype.com/bloombergquint/2024-05/fc2ca81b-8a2e-4076-8655-a07ad75e6779/_1x_1.jpg",
    "source_id": "bloombergquint",
    "source_priority": 9222807,
    "source_url": "https://www.bloombergquint.com",
    "source_icon": "https://i.bytvi.com/domain_icons/bloombergquint.png",
    "language": "english",
    "country": ["india"],
    "category": ["business"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "ed040f7574b10a97fdd966aee346f045",
    "title": "Meta Removes AI-Generated Influence Campaigns In China, Israel",
    "link": "https://www.ndtvprofit.com/technology/meta-removes-ai-generated-influence-campaigns-in-israel-china",
    "keywords": ["technology", "world", "bloomberg"],
    "creator": ["Aisha Counts"],
    "video_url": null,
    "description": "Meta, the parent of Facebook, Instagram and WhatsApp, has seen threat actors rely on AI to produce fake images, videos and text in an effort to influence users on its sites.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-30 01:02:04",
    "image_url": "https://media.assettype.com/bloombergquint/2024-05/bb1d9b2d-fc49-409d-b765-908d0ef49ba3/_1x_1.jpg",
    "source_id": "bloombergquint",
    "source_priority": 9222807,
    "source_url": "https://www.bloombergquint.com",
    "source_icon": "https://i.bytvi.com/domain_icons/bloombergquint.png",
    "language": "english",
    "country": ["india"],
    "category": ["business"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "5e847ecb57f7fb451b1e1408c62f9a23",
    "title": "Israel Sees Seven More Months Of Fighting To Defeat Hamas",
    "link": "https://www.ndtvprofit.com/world/israel-sees-seven-more-months-of-fighting-in-gaza-until-hamas-is-crushed",
    "keywords": ["world", "bloomberg"],
    "creator": ["Alisa Odenheimer"],
    "video_url": null,
    "description": "The comments will do little to raise the spirits of mediators like the US and Qatar.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-30 01:00:27",
    "image_url": "https://media.assettype.com/bloombergquint/2024-05/8b8e992a-2d1d-48eb-a79c-01d66e9c735f/_1x_1.jpg",
    "source_id": "bloombergquint",
    "source_priority": 9222807,
    "source_url": "https://www.bloombergquint.com",
    "source_icon": "https://i.bytvi.com/domain_icons/bloombergquint.png",
    "language": "english",
    "country": ["india"],
    "category": ["business"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "b31d0049301da8d27029aa6e5d63a25c",
    "title": "Toilet Bowl Cleaner Brand Logeski Set to Make a Splash in the Thai Market",
    "link": "https://www.prnewswire.com/apac/news-releases/toilet-bowl-cleaner-brand-logeski-set-to-make-a-splash-in-the-thai-market-302157358.html",
    "keywords": null,
    "creator": null,
    "video_url": null,
    "description":
      "BANGKOK, May 30, 2024 /PRNewswire/ -- Chinese toilet bowl cleaner brand, Logeski, has made waves in its home market with its unique, scrub-free toilet bowl cleaner, earning a stellar reputation among consumers. Now, the Thai market is eagerly awaiting Logeski's arrival. The brand has...",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-30 01:00:00",
    "image_url": "https://mma.prnewswire.com/media/2423283/10000.jpg?p=original",
    "source_id": "prnewswire_apac",
    "source_priority": 1822,
    "source_url": "https://www.prnewswire.com/apac",
    "source_icon": "https://i.bytvi.com/domain_icons/prnewswire_apac.png",
    "language": "english",
    "country": ["maldives", "china", "philippines", "indonesia", "mongolia", "bangladesh", "south korea", "cambodia", "sri lanka", "nepal", "hong kong", "new zealand", "pakistan", "australia", "singapore", "bhutan", "thailand", "brunei", "afghanistan", "fiji", "india", "japan", "malaysia"],
    "category": ["technology", "business"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "e79878f7aacd57f5dc48078bedade069",
    "title": "Hungary Teams Up with Belarus for New Nuclear Reactor",
    "link": "https://oilprice.com/Latest-Energy-News/World-News/Hungary-Teams-Up-with-Belarus-for-New-Nuclear-Reactor.html",
    "keywords": null,
    "creator": ["Josh Owens"],
    "video_url": null,
    "description":
      'As Cold War-style rhetoric continues to intensify in the wake of Sweden and Finland’s accession to NATO, Hungary’s pro-Russian president Viktor Orban is now courting Belarus to expand ties and build Hungary’s second nuclear power plant. On Wednesday, despite European Union sanctions on Russian ally Belarus, Hungarian Foreign Minister Péter Szijjártó visited MInsk, where he publicly stated, "our position is clear: the fewer sanctions, the more cooperation!” The two countries signed a deal in which Belarus...',
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-30 01:00:00",
    "image_url": "https://d32r1sh890xpii.cloudfront.net/news/718x300/2024-05-29_iuanogrde9.jpg",
    "source_id": "oilprice",
    "source_priority": 1511,
    "source_url": "https://oilprice.com",
    "source_icon": "https://i.bytvi.com/domain_icons/oilprice.png",
    "language": "english",
    "country": ["india", "united kingdom", "united states of america", "australia", "singapore"],
    "category": ["business"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "13231afd2d9ef61fce898b285238640e",
    "title": "LG EXPANDS ITS HVAC BUSINESS THROUGH TARGETING B2B CUSTOMERS IN KEY ASIAN MARKETS",
    "link": "https://www.prnewswire.com/apac/news-releases/lg-expands-its-hvac-business-through-targeting-b2b-customers-in-key-asian-markets-302158063.html",
    "keywords": null,
    "creator": null,
    "video_url": null,
    "description":
      "Company Reinforces Industry Leadership with Summit for Technical Consultants from Across Asia SEOUL, South Korea, May 30, 2024 /PRNewswire/ -- LG Electronics (LG) is currently hosting the inaugural LG HVAC Consultant Leaders' Summit – LG Alumni Event – in Seoul, South Korea (May 28-31)....",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-30 01:00:00",
    "image_url": "https://mma.prnewswire.com/media/2424675/LG_HVAC_Consultant_Leaders_Summit_01_resize.jpg?p=original",
    "source_id": "prnewswire_apac",
    "source_priority": 1822,
    "source_url": "https://www.prnewswire.com/apac",
    "source_icon": "https://i.bytvi.com/domain_icons/prnewswire_apac.png",
    "language": "english",
    "country": ["maldives", "china", "philippines", "indonesia", "mongolia", "bangladesh", "south korea", "cambodia", "sri lanka", "nepal", "hong kong", "new zealand", "pakistan", "australia", "singapore", "bhutan", "thailand", "brunei", "afghanistan", "fiji", "india", "japan", "malaysia"],
    "category": ["technology", "business"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "dc10bfcffff7e53ecd7d8d677503ad49",
    "title": "Stock to buy today: E.I.D. - Parry (₹686.45) – BUY",
    "link": "https://www.thehindubusinessline.com/portfolio/technical-analysis/stock-to-buy-today-30-may-2024-eid-parry-rs-686/article68228405.ece",
    "keywords": ["technical analysis"],
    "creator": null,
    "video_url": null,
    "description": "E.I.D. – Parry share price can rise to ₹750",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-30 01:00:00",
    "image_url": "https://bl-i.thgim.com/public/incoming/zcy9hh/article68228454.ece/alternates/LANDSCAPE_1200/E.I.D.%20-%20Parry.jpg",
    "source_id": "thehindubusinessline",
    "source_priority": 40538125,
    "source_url": "https://www.thehindubusinessline.com",
    "source_icon": "https://i.bytvi.com/domain_icons/thehindubusinessline.png",
    "language": "english",
    "country": ["india"],
    "category": ["business"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "1edf80205d2369b0a05a2b05c0ec2f8f",
    "title": "Pre-market action: Here's the trade setup for today's session",
    "link": "https://economictimes.indiatimes.com/markets/stocks/news/pre-market-action-heres-the-trade-setup-for-todays-session/articleshow/110547964.cms",
    "keywords": null,
    "creator": null,
    "video_url": null,
    "description":
      '"On the domestic front, though FII selling intensity has reduced, the caution is increasing as we near the big event outcome which is resulting in profit booking. The volatility is expected to be heightened in coming sessions, thus it\'s advisable to traders to stay on the sidelines and not get too aggressive. The weak global cues are further adding to the nervousness and thus markets are likely to remain weak in near future," said Siddhartha Khemka, Head - Retail Research, Motilal Oswal.',
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-30 00:59:57",
    "image_url": "https://img.etimg.com/thumb/msid-110547951,width-210,height-158,imgsize-111681,resizemode-75/markets-shutter.jpg",
    "source_id": "economictimes_indiatimes",
    "source_priority": 376,
    "source_url": "https://economictimes.indiatimes.com",
    "source_icon": "https://i.bytvi.com/domain_icons/economictimes_indiatimes.png",
    "language": "english",
    "country": ["india"],
    "category": ["business"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "453056496a14e014efe111443bb654dd",
    "title": "Paytm denies report claiming Gautam Adani stake talks with Vijay Shekhar Sharma: ‘Speculative’",
    "link": "https://www.hindustantimes.com/business/paytm-share-price-today-paytm-denies-report-claiming-gautam-adani-stake-talks-with-vijay-shekhar-sharma-speculative-101716956357282.html",
    "keywords": ["business"],
    "creator": null,
    "video_url": null,
    "description": "Paytm share price today: Paytm said the reports are speculative and the company is not engaged in any discussions with the Adani Group.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:28:50",
    "image_url": "https://www.hindustantimes.com/ht-img/img/2024/05/29/1600x900/INDIA-PAYTM-39_1707112868335_1716956818657.jpg",
    "source_id": "hindustantimes",
    "source_priority": 933,
    "source_url": "http://www.hindustantimes.com",
    "source_icon": "https://i.bytvi.com/domain_icons/hindustantimes.png",
    "language": "english",
    "country": ["india"],
    "category": ["business"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "a947cc1a1433f4a6286984ec71f8da57",
    "title": "Paytm denies report claiming Gautam Adani stake talks with Vijay Shekhar Sharma: ‘Speculative’ - Hindustan Times",
    "link":
      "https://news.google.com/rss/articles/CBMisAFodHRwczovL3d3dy5oaW5kdXN0YW50aW1lcy5jb20vYnVzaW5lc3MvcGF5dG0tc2hhcmUtcHJpY2UtdG9kYXktcGF5dG0tZGVuaWVzLXJlcG9ydC1jbGFpbWluZy1nYXV0YW0tYWRhbmktc3Rha2UtdGFsa3Mtd2l0aC12aWpheS1zaGVraGFyLXNoYXJtYS1zcGVjdWxhdGl2ZS0xMDE3MTY5NTYzNTcyODIuaHRtbNIBtAFodHRwczovL3d3dy5oaW5kdXN0YW50aW1lcy5jb20vYnVzaW5lc3MvcGF5dG0tc2hhcmUtcHJpY2UtdG9kYXktcGF5dG0tZGVuaWVzLXJlcG9ydC1jbGFpbWluZy1nYXV0YW0tYWRhbmktc3Rha2UtdGFsa3Mtd2l0aC12aWpheS1zaGVraGFyLXNoYXJtYS1zcGVjdWxhdGl2ZS0xMDE3MTY5NTYzNTcyODItYW1wLmh0bWw?oc=5",
    "keywords": null,
    "creator": null,
    "video_url": null,
    "description":
      "Paytm denies report claiming Gautam Adani stake talks with Vijay Shekhar Sharma: ‘Speculative’ Hindustan TimesAdani Paytm report: Congress attacks PM Modi, says 'Paytm was Pay to Modi' The Economic TimesNewsletter | Vijay Shekhar Sharma seeks buyers for a stake in One 97 Communications? Insurance needs for adven CNBCTV18Paytm terms Adani stake buy reports as 'speculative'; stock hits upper circuit The Indian ExpressAdani in talks with Paytm to acquire stake? Speculative, says fintech firm Business Standard",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:28:50",
    "image_url": null,
    "source_id": "google",
    "source_priority": 14,
    "source_url": "https://news.google.com",
    "source_icon": "https://i.bytvi.com/domain_icons/google.png",
    "language": "english",
    "country": ["india"],
    "category": ["business"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  // {
  //   "article_id": "20078121922c257fe210c6967a09d4d3",
  //   "title": "Should you buy IRCTC, NBCC shares? What Stock Market expert said",
  //   "link": "https://www.news9live.com/business/markets/should-you-buy-irctc-nbcc-shares-what-stock-market-expert-said-2554224",
  //   "keywords": ["markets"],
  //   "creator": ["Biplob Ghosal"],
  //   "video_url": null,
  //   "description": "Buy Call on IRCTC and NBCC. Stock Market expert Arun Mantri said IRCTC and NBCC stocks can be purchased on dips. The expert backed the shares to gain in long term.",
  //   "content": "ONLY AVAILABLE IN PAID PLANS",
  //   "pubDate": "2024-05-29 04:28:00",
  //   "image_url": "https://images.news9live.com/wp-content/uploads/2024/05/IRCTC-and-NBCC-share-price.png",
  //   "source_id": "news9live",
  //   "source_priority": 193096,
  //   "source_url": "https://www.news9live.com",
  //   "source_icon": "https://i.bytvi.com/domain_icons/news9live.png",
  //   "language": "english",
  //   "country": ["india"],
  //   "category": ["business"],
  //   "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
  //   "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  // },
  {
    "article_id": "c0a49c54a7198e1474380dfdb66d7c26",
    "title": "Future of green jobs holds immense promise in India: Ramesh Alluri Reddy, TeamLease Degree Apprenticeship",
    "link": "https://economictimes.indiatimes.com/small-biz/sustainability/future-of-green-jobs-holds-immense-promise-in-india-ramesh-alluri-reddy-teamlease-degree-apprenticeship/articleshow/110520680.cms",
    "keywords": null,
    "creator": null,
    "video_url": null,
    "description": "India’s transition towards sustainability holds immense potential in creating new employment opportunities.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:28:00",
    "image_url": "https://img.etimg.com/thumb/msid-110520708,width-300,height-225,imgsize-211030,resizemode-75/green-jobs-istock.jpg",
    "source_id": "economictimes_indiatimes",
    "source_priority": 376,
    "source_url": "https://economictimes.indiatimes.com",
    "source_icon": "https://i.bytvi.com/domain_icons/economictimes_indiatimes.png",
    "language": "english",
    "country": ["india"],
    "category": ["business"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "cfa5429dfb96684039c20b1839dc5a18",
    "title": "Currency market today: Rupee falls 9 paise to 83.27 against US dollar in early trade",
    "link": "https://www.thehindubusinessline.com/markets/forex/currency-market-today-rupee-falls-9-paise-to-8327-against-us-dollar-in-early-trade/article68227374.ece",
    "keywords": ["forex"],
    "creator": null,
    "video_url": null,
    "description": "At the interbank foreign exchange market, the rupee opened at 83.22 and lost further ground to trade at 83.27 against the greenback",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:27:15",
    "image_url": "https://bl-i.thgim.com/public/incoming/na9748/article68227379.ece/alternates/LANDSCAPE_1200/IMG_bl15_gavel_lead_pic_2_1_CN96E0OL.jpg",
    "source_id": "thehindubusinessline",
    "source_priority": 40538125,
    "source_url": "https://www.thehindubusinessline.com",
    "source_icon": "https://i.bytvi.com/domain_icons/thehindubusinessline.png",
    "language": "english",
    "country": ["india"],
    "category": ["business"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  // {
  //   "article_id": "2e0634745ddfde816526bcb01012f632",
  //   "title": "Gautam Adani eyeing stake in Paytm? Here's what Vijay Shekhar Sharma-led company has to say",
  //   "link": "https://www.dnaindia.com/business/report-gautam-adani-eyeing-stake-in-paytm-here-s-what-vijay-shekhar-sharma-led-company-has-to-say-3091123",
  //   "keywords": ["business"],
  //   "creator": ["Srishty Choudhury"],
  //   "video_url": null,
  //   "description": "This speculation came amid increasing losses at Paytm following the RBI's ban on Paytm Payments Bank Ltd.",
  //   "content": "ONLY AVAILABLE IN PAID PLANS",
  //   "pubDate": "2024-05-29 04:26:00",
  //   "image_url": "https://cdn.dnaindia.com/sites/default/files/styles/third/public/2024/05/29/2636098-paytm.jpg",
  //   "source_id": "dnaindia",
  //   "source_priority": 18388,
  //   "source_url": "https://www.dnaindia.com",
  //   "source_icon": null,
  //   "language": "english",
  //   "country": ["india"],
  //   "category": ["business"],
  //   "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
  //   "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  // },
  {
    "article_id": "892646904f6de08902768c81c3cf2b08",
    "title": "Two mutual fund schemes turned Rs 10 lakh to Rs 1 crore in 10 years of Modi govt",
    "link": "https://economictimes.indiatimes.com/mf/analysis/two-mutual-fund-schemes-turned-rs-10-lakh-to-rs-1-crore-in-10-years-of-modi-govt/articleshow/110520666.cms",
    "keywords": null,
    "creator": null,
    "video_url": null,
    "description": "ETMutualFunds analysis reveals two schemes turning Rs 10 lakh into Rs 1 crore under Modi-led government. Nippon India Small Cap Fund and SBI Small Cap Fund deliver impressive CAGRs. Investors should consider risk appetite and goals before making investment decisions.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:23:23",
    "image_url": "https://img.etimg.com/thumb/msid-110521004,width-300,height-225,imgsize-40752,resizemode-75/mutual-funds.jpg",
    "source_id": "economictimes_indiatimes",
    "source_priority": 376,
    "source_url": "https://economictimes.indiatimes.com",
    "source_icon": "https://i.bytvi.com/domain_icons/economictimes_indiatimes.png",
    "language": "english",
    "country": ["india"],
    "category": ["business"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "aa546e6b996b2c91e996535d73837a98",
    "title": "How China pulled so far ahead on industrial policy",
    "link": "https://economictimes.indiatimes.com/small-biz/trade/exports/insights/how-china-pulled-so-far-ahead-on-industrial-policy/articleshow/110520557.cms",
    "keywords": null,
    "creator": null,
    "video_url": null,
    "description": "The problem for the West, though, is that China's industrial dominance is underpinned by decades of experience using the power of a one-party state to pull all the levers of government and banking, while encouraging frenetic competition among private companies.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:23:11",
    "image_url": "https://img.etimg.com/thumb/msid-110520623,width-650,height-488,imgsize-351858,resizemode-75/undefined-29-.jpg",
    "source_id": "economictimes_indiatimes",
    "source_priority": 376,
    "source_url": "https://economictimes.indiatimes.com",
    "source_icon": "https://i.bytvi.com/domain_icons/economictimes_indiatimes.png",
    "language": "english",
    "country": ["india"],
    "category": ["business"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  // {
  //   "article_id": "0b87e818e373aeb2b86972f908c42ac0",
  //   "title": "Concord Biotech share price surges 20% as Kotak upgrades the stock to an add",
  //   "link": "https://www.livemint.com/market/stock-market-news/concord-biotech-share-price-opens-20-hgher-after-kotak-upgrades-the-stock-to-an-add-11716956345938.html",
  //   "keywords": null,
  //   "creator": null,
  //   "video_url": null,
  //   "description": "Concord Biotech share price vaulted 20 per cent to open at ₹1,670 on Wednesday, May 29, on BSE, defying weak market sentiment.",
  //   "content": "ONLY AVAILABLE IN PAID PLANS",
  //   "pubDate": "2024-05-29 04:21:34",
  //   "image_url": "https://www.livemint.com/lm-img/static/1yr/newmintdefault-120.png",
  //   "source_id": "livemint",
  //   "source_priority": 7134,
  //   "source_url": "https://www.livemint.com",
  //   "source_icon": "https://i.bytvi.com/domain_icons/livemint.png",
  //   "language": "english",
  //   "country": ["india"],
  //   "category": ["business"],
  //   "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
  //   "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  // },
  {
    "article_id": "86125bb5595579393fd3865a48b7aab7",
    "title": "Income Tax department issues fresh reminder on PAN-Aadhaar linking to avoid higher TDS. Check details",
    "link": "https://www.indiatvnews.com/business/news/income-tax-department-issues-reminder-on-pan-aadhaar-linking-to-avoid-higher-tds-check-last-date-and-other-details-2024-05-29-933955",
    "keywords": null,
    "creator": null,
    "video_url": null,
    "description":
      'The Income Tax Department has issued a fresh notification to taxpayers, asking them to link their Permanent Account Number (PAN) with Aadhaar by May 31, 2024. The tax department posted this reminder reminder on X, highlighting the importance of meeting the deadline to avoid higher tax deductions at source (TDS). "Kind attention taxpayers, please link your PAN with Aadhaar before May 31, 2024... Linking your PAN with your Aadhaar by May 31 ensures you don’t face higher tax deduction/tax collection under Section 206AA and 206CC of the Income Tax Act, 1961, due to an inoperative PAN for transactions entered into before March 31, 2024," said the I-T Department.',
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:21:29",
    "image_url": "https://resize.indiatvnews.com/en/resize/newbucket/715_-/2024/05/pan-aadhaar-1593013367-1716956441.jpg",
    "source_id": "indiatvnews",
    "source_priority": 10055,
    "source_url": "https://www.indiatvnews.com",
    "source_icon": "https://i.bytvi.com/domain_icons/indiatvnews.png",
    "language": "english",
    "country": ["india"],
    "category": ["business"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
]

export default business
