const business = [
  {
    "article_id": "453056496a14e014efe111443bb654dd",
    "title": "Paytm denies report claiming Gautam Adani stake talks with Vijay Shekhar Sharma: ‘Speculative’",
    "link": "https://www.hindustantimes.com/business/paytm-share-price-today-paytm-denies-report-claiming-gautam-adani-stake-talks-with-vijay-shekhar-sharma-speculative-101716956357282.html",
    "keywords": ["business"],
    "creator": null,
    "video_url": null,
    "description": "Paytm share price today: Paytm said the reports are speculative and the company is not engaged in any discussions with the Adani Group.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:28:50",
    "image_url": "https://www.hindustantimes.com/ht-img/img/2024/05/29/1600x900/INDIA-PAYTM-39_1707112868335_1716956818657.jpg",
    "source_id": "hindustantimes",
    "source_priority": 933,
    "source_url": "http://www.hindustantimes.com",
    "source_icon": "https://i.bytvi.com/domain_icons/hindustantimes.png",
    "language": "english",
    "country": ["india"],
    "category": ["business"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "a947cc1a1433f4a6286984ec71f8da57",
    "title": "Paytm denies report claiming Gautam Adani stake talks with Vijay Shekhar Sharma: ‘Speculative’ - Hindustan Times",
    "link":
      "https://news.google.com/rss/articles/CBMisAFodHRwczovL3d3dy5oaW5kdXN0YW50aW1lcy5jb20vYnVzaW5lc3MvcGF5dG0tc2hhcmUtcHJpY2UtdG9kYXktcGF5dG0tZGVuaWVzLXJlcG9ydC1jbGFpbWluZy1nYXV0YW0tYWRhbmktc3Rha2UtdGFsa3Mtd2l0aC12aWpheS1zaGVraGFyLXNoYXJtYS1zcGVjdWxhdGl2ZS0xMDE3MTY5NTYzNTcyODIuaHRtbNIBtAFodHRwczovL3d3dy5oaW5kdXN0YW50aW1lcy5jb20vYnVzaW5lc3MvcGF5dG0tc2hhcmUtcHJpY2UtdG9kYXktcGF5dG0tZGVuaWVzLXJlcG9ydC1jbGFpbWluZy1nYXV0YW0tYWRhbmktc3Rha2UtdGFsa3Mtd2l0aC12aWpheS1zaGVraGFyLXNoYXJtYS1zcGVjdWxhdGl2ZS0xMDE3MTY5NTYzNTcyODItYW1wLmh0bWw?oc=5",
    "keywords": null,
    "creator": null,
    "video_url": null,
    "description":
      "Paytm denies report claiming Gautam Adani stake talks with Vijay Shekhar Sharma: ‘Speculative’ Hindustan TimesAdani Paytm report: Congress attacks PM Modi, says 'Paytm was Pay to Modi' The Economic TimesNewsletter | Vijay Shekhar Sharma seeks buyers for a stake in One 97 Communications? Insurance needs for adven CNBCTV18Paytm terms Adani stake buy reports as 'speculative'; stock hits upper circuit The Indian ExpressAdani in talks with Paytm to acquire stake? Speculative, says fintech firm Business Standard",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:28:50",
    "image_url": null,
    "source_id": "google",
    "source_priority": 14,
    "source_url": "https://news.google.com",
    "source_icon": "https://i.bytvi.com/domain_icons/google.png",
    "language": "english",
    "country": ["india"],
    "category": ["business"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "20078121922c257fe210c6967a09d4d3",
    "title": "Should you buy IRCTC, NBCC shares? What Stock Market expert said",
    "link": "https://www.news9live.com/business/markets/should-you-buy-irctc-nbcc-shares-what-stock-market-expert-said-2554224",
    "keywords": ["markets"],
    "creator": ["Biplob Ghosal"],
    "video_url": null,
    "description": "Buy Call on IRCTC and NBCC. Stock Market expert Arun Mantri said IRCTC and NBCC stocks can be purchased on dips. The expert backed the shares to gain in long term.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:28:00",
    "image_url": "https://images.news9live.com/wp-content/uploads/2024/05/IRCTC-and-NBCC-share-price.png",
    "source_id": "news9live",
    "source_priority": 193096,
    "source_url": "https://www.news9live.com",
    "source_icon": "https://i.bytvi.com/domain_icons/news9live.png",
    "language": "english",
    "country": ["india"],
    "category": ["business"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "c0a49c54a7198e1474380dfdb66d7c26",
    "title": "Future of green jobs holds immense promise in India: Ramesh Alluri Reddy, TeamLease Degree Apprenticeship",
    "link": "https://economictimes.indiatimes.com/small-biz/sustainability/future-of-green-jobs-holds-immense-promise-in-india-ramesh-alluri-reddy-teamlease-degree-apprenticeship/articleshow/110520680.cms",
    "keywords": null,
    "creator": null,
    "video_url": null,
    "description": "India’s transition towards sustainability holds immense potential in creating new employment opportunities.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:28:00",
    "image_url": "https://img.etimg.com/thumb/msid-110520708,width-300,height-225,imgsize-211030,resizemode-75/green-jobs-istock.jpg",
    "source_id": "economictimes_indiatimes",
    "source_priority": 376,
    "source_url": "https://economictimes.indiatimes.com",
    "source_icon": "https://i.bytvi.com/domain_icons/economictimes_indiatimes.png",
    "language": "english",
    "country": ["india"],
    "category": ["business"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "cfa5429dfb96684039c20b1839dc5a18",
    "title": "Currency market today: Rupee falls 9 paise to 83.27 against US dollar in early trade",
    "link": "https://www.thehindubusinessline.com/markets/forex/currency-market-today-rupee-falls-9-paise-to-8327-against-us-dollar-in-early-trade/article68227374.ece",
    "keywords": ["forex"],
    "creator": null,
    "video_url": null,
    "description": "At the interbank foreign exchange market, the rupee opened at 83.22 and lost further ground to trade at 83.27 against the greenback",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:27:15",
    "image_url": "https://bl-i.thgim.com/public/incoming/na9748/article68227379.ece/alternates/LANDSCAPE_1200/IMG_bl15_gavel_lead_pic_2_1_CN96E0OL.jpg",
    "source_id": "thehindubusinessline",
    "source_priority": 40538125,
    "source_url": "https://www.thehindubusinessline.com",
    "source_icon": "https://i.bytvi.com/domain_icons/thehindubusinessline.png",
    "language": "english",
    "country": ["india"],
    "category": ["business"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "2e0634745ddfde816526bcb01012f632",
    "title": "Gautam Adani eyeing stake in Paytm? Here's what Vijay Shekhar Sharma-led company has to say",
    "link": "https://www.dnaindia.com/business/report-gautam-adani-eyeing-stake-in-paytm-here-s-what-vijay-shekhar-sharma-led-company-has-to-say-3091123",
    "keywords": ["business"],
    "creator": ["Srishty Choudhury"],
    "video_url": null,
    "description": "This speculation came amid increasing losses at Paytm following the RBI's ban on Paytm Payments Bank Ltd.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:26:00",
    "image_url": "https://cdn.dnaindia.com/sites/default/files/styles/third/public/2024/05/29/2636098-paytm.jpg",
    "source_id": "dnaindia",
    "source_priority": 18388,
    "source_url": "https://www.dnaindia.com",
    "source_icon": null,
    "language": "english",
    "country": ["india"],
    "category": ["business"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "892646904f6de08902768c81c3cf2b08",
    "title": "Two mutual fund schemes turned Rs 10 lakh to Rs 1 crore in 10 years of Modi govt",
    "link": "https://economictimes.indiatimes.com/mf/analysis/two-mutual-fund-schemes-turned-rs-10-lakh-to-rs-1-crore-in-10-years-of-modi-govt/articleshow/110520666.cms",
    "keywords": null,
    "creator": null,
    "video_url": null,
    "description": "ETMutualFunds analysis reveals two schemes turning Rs 10 lakh into Rs 1 crore under Modi-led government. Nippon India Small Cap Fund and SBI Small Cap Fund deliver impressive CAGRs. Investors should consider risk appetite and goals before making investment decisions.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:23:23",
    "image_url": "https://img.etimg.com/thumb/msid-110521004,width-300,height-225,imgsize-40752,resizemode-75/mutual-funds.jpg",
    "source_id": "economictimes_indiatimes",
    "source_priority": 376,
    "source_url": "https://economictimes.indiatimes.com",
    "source_icon": "https://i.bytvi.com/domain_icons/economictimes_indiatimes.png",
    "language": "english",
    "country": ["india"],
    "category": ["business"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "aa546e6b996b2c91e996535d73837a98",
    "title": "How China pulled so far ahead on industrial policy",
    "link": "https://economictimes.indiatimes.com/small-biz/trade/exports/insights/how-china-pulled-so-far-ahead-on-industrial-policy/articleshow/110520557.cms",
    "keywords": null,
    "creator": null,
    "video_url": null,
    "description": "The problem for the West, though, is that China's industrial dominance is underpinned by decades of experience using the power of a one-party state to pull all the levers of government and banking, while encouraging frenetic competition among private companies.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:23:11",
    "image_url": "https://img.etimg.com/thumb/msid-110520623,width-650,height-488,imgsize-351858,resizemode-75/undefined-29-.jpg",
    "source_id": "economictimes_indiatimes",
    "source_priority": 376,
    "source_url": "https://economictimes.indiatimes.com",
    "source_icon": "https://i.bytvi.com/domain_icons/economictimes_indiatimes.png",
    "language": "english",
    "country": ["india"],
    "category": ["business"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "0b87e818e373aeb2b86972f908c42ac0",
    "title": "Concord Biotech share price surges 20% as Kotak upgrades the stock to an add",
    "link": "https://www.livemint.com/market/stock-market-news/concord-biotech-share-price-opens-20-hgher-after-kotak-upgrades-the-stock-to-an-add-11716956345938.html",
    "keywords": null,
    "creator": null,
    "video_url": null,
    "description": "Concord Biotech share price vaulted 20 per cent to open at ₹1,670 on Wednesday, May 29, on BSE, defying weak market sentiment.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:21:34",
    "image_url": "https://www.livemint.com/lm-img/static/1yr/newmintdefault-120.png",
    "source_id": "livemint",
    "source_priority": 7134,
    "source_url": "https://www.livemint.com",
    "source_icon": "https://i.bytvi.com/domain_icons/livemint.png",
    "language": "english",
    "country": ["india"],
    "category": ["business"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "86125bb5595579393fd3865a48b7aab7",
    "title": "Income Tax department issues fresh reminder on PAN-Aadhaar linking to avoid higher TDS. Check details",
    "link": "https://www.indiatvnews.com/business/news/income-tax-department-issues-reminder-on-pan-aadhaar-linking-to-avoid-higher-tds-check-last-date-and-other-details-2024-05-29-933955",
    "keywords": null,
    "creator": null,
    "video_url": null,
    "description":
      'The Income Tax Department has issued a fresh notification to taxpayers, asking them to link their Permanent Account Number (PAN) with Aadhaar by May 31, 2024. The tax department posted this reminder reminder on X, highlighting the importance of meeting the deadline to avoid higher tax deductions at source (TDS). "Kind attention taxpayers, please link your PAN with Aadhaar before May 31, 2024... Linking your PAN with your Aadhaar by May 31 ensures you don’t face higher tax deduction/tax collection under Section 206AA and 206CC of the Income Tax Act, 1961, due to an inoperative PAN for transactions entered into before March 31, 2024," said the I-T Department.',
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:21:29",
    "image_url": "https://resize.indiatvnews.com/en/resize/newbucket/715_-/2024/05/pan-aadhaar-1593013367-1716956441.jpg",
    "source_id": "indiatvnews",
    "source_priority": 10055,
    "source_url": "https://www.indiatvnews.com",
    "source_icon": "https://i.bytvi.com/domain_icons/indiatvnews.png",
    "language": "english",
    "country": ["india"],
    "category": ["business"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
]

export default business
