const entertainment = [
  {
    "article_id": "3105307834ad57885145a80ceb1c1b3c",
    "title": "Harvey Weinstein Eager to Fight Rape Retrial as Prosecutors Weigh More Charges",
    "link": "https://www.newsr.in/n/Celebrities/1zqvn1kzdw/Harvey-Weinstein-Eager-to-Fight-Rape-Retrial-as.htm",
    "keywords": ["celebrities"],
    "creator": null,
    "video_url": null,
    "description":
      "Harvey Weinstein may be facing new criminal charges ahead of his rape retrial -- but whether they come through or not ... the guy's eager to get before another jury to clear his name. The disgraced Hollywood mogul was in court Wednesday in NYC,...Reported by TMZ.com 47 minutes ago.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 22:47:33",
    "image_url": null,
    "source_id": "newsr",
    "source_priority": 29095901,
    "source_url": "https://www.newsr.in",
    "source_icon": "https://i.bytvi.com/domain_icons/newsr.png",
    "language": "english",
    "country": ["india"],
    "category": ["entertainment"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "8b32ec489a491068b429547a4746cc6c",
    "title": "Tamannaah Bhatia Holds Vijay Varma Close As They Pose for Paps at Aranmanai 4 Screening | Watch",
    "link": "https://www.news18.com/movies/tamannaah-bhatia-holds-vijay-varma-close-as-they-pose-for-paps-at-aranmanai-4-screening-watch-8909479.html",
    "keywords": ["movies"],
    "creator": null,
    "video_url": null,
    "description": "Tamannaah Bhatia-starrer Aranmanai 4 is running exceptionally well at the box office. It has become one of the highest-grossing Tamil movies of 2024.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 22:46:13",
    "image_url": "https://images.news18.com/ibnlive/uploads/2024/05/tamannaah-bhatia-and-vijay-varma-2024-05-a803d76afd455dc255a7b01abb320700-3x2.jpg",
    "source_id": "news18",
    "source_priority": 6644,
    "source_url": "https://www.news18.com",
    "source_icon": "https://i.bytvi.com/domain_icons/news18.png",
    "language": "english",
    "country": ["india"],
    "category": ["entertainment"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  // {
  //   "article_id": "0eb43294f642d11d3c7fc71bd6208767",
  //   "title": "Jason, Kylie Kelce Get Free Dinner Offer From Mayor After Run-In W/ Angry Fan",
  //   "link": "https://www.newsr.in/n/Celebrities/1zqvn1kz6e/Jason-Kylie-Kelce-Get-Free-Dinner-Offer-From.htm",
  //   "keywords": ["celebrities"],
  //   "creator": null,
  //   "video_url": null,
  //   "description":
  //     "Jason and Kylie Kelce are not only welcome in Margate, NJ ... but they've also been invited to have a free meal on the mayor's dime -- this after an out-of-control fan threatened the couple wouldn't be allowed inside town limits after turning down...Reported by TMZ.com 19 minutes ago.",
  //   "content": "ONLY AVAILABLE IN PAID PLANS",
  //   "pubDate": "2024-05-29 21:56:41",
  //   "image_url": null,
  //   "source_id": "newsr",
  //   "source_priority": 29095901,
  //   "source_url": "https://www.newsr.in",
  //   "source_icon": "https://i.bytvi.com/domain_icons/newsr.png",
  //   "language": "english",
  //   "country": ["india"],
  //   "category": ["entertainment"],
  //   "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
  //   "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  // },
  {
    "article_id": "3e1bd0efc843114d58dd3a3d27a65ca4",
    "title": "Apathetic Bystander Watches Man Get Robbed at Knifepoint at Taking Back Sunday Show",
    "link": "https://www.newsr.in/n/Celebrities/1zqvn1kz6d/Apathetic-Bystander-Watches-Man-Get-Robbed-at-Knifepoint.htm",
    "keywords": ["celebrities"],
    "creator": null,
    "video_url": null,
    "description":
      "A man says he got robbed at knifepoint after a Taking Back Sunday concert last week -- and he's got the whole thing on video ... with some dude just standing by and watching it all. The alleged victim's name is Brandon -- a sound specialist for...Reported by TMZ.com 19 minutes ago.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 21:56:41",
    "image_url": null,
    "source_id": "newsr",
    "source_priority": 29095901,
    "source_url": "https://www.newsr.in",
    "source_icon": "https://i.bytvi.com/domain_icons/newsr.png",
    "language": "english",
    "country": ["india"],
    "category": ["entertainment"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "da84be5082ee15e2cf127f81571a8c60",
    "title": "Nushrratt Bharuccha Faces Backlash for Posting 'All Eyes On Rafah': 'You Were in Israel When Hamas Attacked'",
    "link": "https://www.news18.com/movies/nushrratt-bharuccha-faces-backlash-for-posting-all-eyes-on-rafah-you-were-in-israel-when-hamas-attacked-8909466.html",
    "keywords": ["movies"],
    "creator": null,
    "video_url": null,
    "description": "Actress Nushrratt Bharuccha has been receiving severe criticism for sharing the viral template 'All Eyes On Rafah' on her Instagram story.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 21:43:04",
    "image_url": "https://images.news18.com/ibnlive/uploads/2024/05/nushrratt-bharuccha-gets-trolled-for-posting-all-eyes-on-rafah-2024-05-b04b608c30fb831011b9b2cdb7274aa1-3x2.jpg",
    "source_id": "news18",
    "source_priority": 6644,
    "source_url": "https://www.news18.com",
    "source_icon": "https://i.bytvi.com/domain_icons/news18.png",
    "language": "english",
    "country": ["india"],
    "category": ["entertainment"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "d5fb28b8d0386d2b76e945a8aefa67cb",
    "title": "Dragon Ball Super Blu-Ray Box Set Comes With 10 Steelbook Cases",
    "link": "https://www.gamespot.com/articles/dragon-ball-super-blu-ray-box-set-comes-with-10-steelbook-cases/1100-6523787/?ftag=CAD-01-10abi2f",
    "keywords": null,
    "creator": ["Darryn Bonthuys"],
    "video_url": null,
    "description":
      "The 2010s were a great time to be a Dragon Ball fan, as the franchise made a huge return to TV with Dragon Ball Super. Set a few years after the Majin Buu saga, Dragon Ball Super saw Goku, Vegeta, the rest of Earth's mightiest warriors, and Krillin face new threats across the entire universe. If you've been looking to rewatch this entire saga, preorders are now live for Dragon Ball Super: The Complete Collection on Blu-ray ahead of its July 31 release.Preorder at Crunchyroll Priced at $180 on the Crunchyroll Store (normally $200), this set includes 20 Blu-ray discs in 10 very stylish steelbook cases. They're all contained inside of a slick slipcase box with slots for each steelbook. The box features the dragon Shenron on the front and other cool decorative details with a metallic finish. You couldn't wish for a better way to store these Blu-rays, even if you did summon Shenron!Dragon Ball Super: The Complete CollectionGallery As for the extras, there's a whole lot here to enjoy. The bonus content ranges from cleaned-up credit sequences to interviews with the voice actor cast of the English dub, and there are a few other cute extras to enjoy as well. Here's the full list:Catching Up on the Dragon Ball Universe: Sonny Strait and Savannah LigaluppiCatching Up on the Dragon Ball Universe: Christopher R. Sabat and Hero D. SabatTextless Opening and Closing SongsWatching Dragon Ball Super: with Jason Douglas and Ian SinclairAnime Expo 2017: Interview with Sean Schemmel and Jason DouglasDragon Ball Super: An Interview with Sean SchemmelCoffee Break with Mai and TrunksDragon Ball Super at Anime Expo 2018: Interviews with Sonny Strait, Matthew Mercer, and Kyle HebertDragon Ball Super: Rawly Pickens and Chuck Huber Answer TwitterDragon Ball Super: Two Humans and an AndroidDragon Ball Super: Twitter Q&A with Sarah Wiedenheft and Dawn BennettDragon Ball Super: Interview with Patrick Seitz and Kyle HebertIf you haven't watched Dragon Ball Super, you're missing out on a very intense sequel series to Dragon Ball Z. The show saw both Goku and Vegeta unlock more powerful Super Saiyan transformations, as well as get knocked down several pegs on the power level ladder when they crossed paths with absurdly strong characters like Beerus, the god of destruction, and warriors from other universes. Several Dragon Ball Super feature films were also released, and two of them were adapted into the main anime series. They're worth checking out if you want to skip through a season or two of the anime, and witness some incredible animation in the process as well.Dragon Ball: Battle of Gods -- $26 ($35)Dragon Ball Super: Resurrection of F -- $26 ($35)Dragon Ball: Broly The Movie -- $27 ($35)Dragon Ball Super: Super Hero -- $20 ($35)Lastly, you can complete your collection with some classic Dragon Ball anime! Dragon Ball Z still holds up as an action-packed romp across the cosmos, and with Amazon's exclusive collector's set, you can get all nine seasons for $168 on Blu-ray. Alternatively, the DVD box set of Dragon Ball GT is pretty cheap, and while it wasn't well-received during its first run, fans have come around to this sort-of-canon Dragon Ball Z sequel series over the years. Its handcrafted animation still looks fantastic, and the back-to-basics adventure approach made for a fun show. Plus, it introduced the Super Saiyan 4 transformation, which is the best Super Saiyan form.Dragon Ball Z: The Complete Collection (Blu-ray) -- $169Dragon Ball GT: The Complete Series (DVD) -- $39 ($70)",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 21:19:00",
    "image_url": "https://www.gamespot.com/a/uploads/screen_medium/1601/16018044/4309975-db-super-main.jpg",
    "source_id": "gamespot",
    "source_priority": 476,
    "source_url": "https://www.gamespot.com",
    "source_icon": "https://i.bytvi.com/domain_icons/gamespot.png",
    "language": "english",
    "country": ["india", "singapore", "united states of america", "australia", "united kingdom"],
    "category": ["entertainment"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  // {
  //   "article_id": "c1b576ca5ca78a092869f31ce221a1ae",
  //   "title": "Latest entertainment News, Live Updates Today May 30, 2024: One Piece Chapter 1116: What new threats await Luffy?",
  //   "link": "https://www.hindustantimes.com/entertainment/latest-entertainment-today-live-updates-may-30-2024-101717016973650.html",
  //   "keywords": ["entertainment"],
  //   "creator": null,
  //   "video_url": null,
  //   "description":
  //     "Welcome to the live updates platform for Hindustan Times. Follow the major news updates, headlines and breaking news stories from the world of entertainment right here. See the latest developments in Bollywood, Hollywood and track the big news stories of the day for May 30, 2024.",
  //   "content": "ONLY AVAILABLE IN PAID PLANS",
  //   "pubDate": "2024-05-29 21:09:33",
  //   "image_url": "https://www.hindustantimes.com/ht-img/img/2024/05/29/1600x900/41f18-16920436013351_1692189855498_1717016667848.webp",
  //   "source_id": "hindustantimes",
  //   "source_priority": 933,
  //   "source_url": "http://www.hindustantimes.com",
  //   "source_icon": "https://i.bytvi.com/domain_icons/hindustantimes.png",
  //   "language": "english",
  //   "country": ["india"],
  //   "category": ["entertainment"],
  //   "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
  //   "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  // },
  // {
  //   "article_id": "f11693c2295fd3dbe8a84a80e6fba047",
  //   "title": "One Piece Chapter 1116: What new threats await Luffy?",
  //   "link": "https://www.hindustantimes.com/entertainment/anime/one-piece-chapter-1116-what-new-threats-await-luffy-101717012088849.html",
  //   "keywords": ["entertainment"],
  //   "creator": null,
  //   "video_url": null,
  //   "description": "Get ready for an epic journey as the Straw Hats navigate perilous waters in One Piece Chapter 1116.",
  //   "content": "ONLY AVAILABLE IN PAID PLANS",
  //   "pubDate": "2024-05-29 21:09:32",
  //   "image_url": "https://www.hindustantimes.com/ht-img/img/2024/05/29/1600x900/41f18-16920436013351_1692189855498_1717016667848.webp",
  //   "source_id": "hindustantimes",
  //   "source_priority": 933,
  //   "source_url": "http://www.hindustantimes.com",
  //   "source_icon": "https://i.bytvi.com/domain_icons/hindustantimes.png",
  //   "language": "english",
  //   "country": ["india"],
  //   "category": ["entertainment"],
  //   "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
  //   "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  // },
  // {
  //   "article_id": "d2881f9d180eae6ce5e1dfc67b2191ef",
  //   "title": "Jill Biden Confirms Mics Will Be Cut Off During Biden-Trump Debate",
  //   "link": "https://www.newsr.in/n/Celebrities/1zqvn1kyz0/Jill-Biden-Confirms-Mics-Will-Be-Cut-Off.htm",
  //   "keywords": ["celebrities"],
  //   "creator": null,
  //   "video_url": null,
  //   "description":
  //     'Jill Biden is promising some semblance of decorum for the first 2024 Presidential debate ... teasing how the moderators will put a stop to any rambling with the hit of a switch. The First Lady stopped by "The View" Wednesday morning, where FLOTUS...Reported by TMZ.com 7 minutes ago.',
  //   "content": "ONLY AVAILABLE IN PAID PLANS",
  //   "pubDate": "2024-05-29 21:05:32",
  //   "image_url": null,
  //   "source_id": "newsr",
  //   "source_priority": 29095901,
  //   "source_url": "https://www.newsr.in",
  //   "source_icon": "https://i.bytvi.com/domain_icons/newsr.png",
  //   "language": "english",
  //   "country": ["india"],
  //   "category": ["entertainment"],
  //   "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
  //   "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  // },
  // {
  //   "article_id": "e3c8516c18dadeca1912f469ab34212f",
  //   "title": "Alexander 'AE' Edwards Says All's Good with Travis Scott After Cannes Brawl",
  //   "link": "https://www.newsr.in/n/Celebrities/1zqvn1kyyz/Alexander-AE-Edwards-Says-All-Good-with.htm",
  //   "keywords": ["celebrities"],
  //   "creator": null,
  //   "video_url": null,
  //   "description":
  //     "Alexander \"AE\" Edwards is reassuring everyone things are all good with Travis Scott after their wild fight at a Cannes Film Festival after-party last week. We got Cher's BF Wednesday at LAX ... and while he didn't dish on what exactly sparked the...Reported by TMZ.com 7 minutes ago.",
  //   "content": "ONLY AVAILABLE IN PAID PLANS",
  //   "pubDate": "2024-05-29 21:05:32",
  //   "image_url": null,
  //   "source_id": "newsr",
  //   "source_priority": 29095901,
  //   "source_url": "https://www.newsr.in",
  //   "source_icon": "https://i.bytvi.com/domain_icons/newsr.png",
  //   "language": "english",
  //   "country": ["india"],
  //   "category": ["entertainment"],
  //   "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
  //   "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  // },
  {
    "article_id": "3ff4d085f859b34a4e82d0d9c05b04f8",
    "title": "Former FTII chief Gajendra Chauhan, whom Payal Kapadia protested against, reacts to her Cannes win: Talent is fine, but...",
    "link": "https://www.dnaindia.com/bollywood/report-former-ftii-chief-gajendra-chauhan-reacts-to-payal-kapadia-s-cannes-win-talent-is-fine-but-3091118",
    "keywords": ["entertainment", "bollywood"],
    "creator": ["Manisha Chauhan"],
    "video_url": null,
    "description": "In 2015, Payal Kapadia and other students protested Gajendra Chauhan's appointment as FTII chairman, believing he lacked the necessary qualifications.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:18:00",
    "image_url": "https://cdn.dnaindia.com/sites/default/files/styles/third/public/2024/05/29/2636093-fotojet-2024-05-29t101453.942-1.jpg",
    "source_id": "dnaindia",
    "source_priority": 18388,
    "source_url": "https://www.dnaindia.com",
    "source_icon": null,
    "language": "english",
    "country": ["india"],
    "category": ["entertainment"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "7660252f5e44268bf2bd041012da713e",
    "title": "KKR On Top Of The World: How Shah Rukh Khan's Team Lit Up Dubai's Burj Khalifa",
    "link": "https://www.ndtv.com/entertainment/kkr-on-top-of-the-world-how-shah-rukh-khans-team-lit-up-dubais-burj-khalifa-5768963#publisher=newsstand",
    "keywords": null,
    "creator": null,
    "video_url": null,
    "description": '"View from the top. It\'s all purple," read the caption on the post',
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:16:26",
    "image_url": "https://c.ndtvimg.com/2024-05/auem9djo_srk_625x300_29_May_24.jpeg",
    "source_id": "ndtv",
    "source_priority": 1204,
    "source_url": "http://www.ndtv.com",
    "source_icon": "https://i.bytvi.com/domain_icons/ndtv.png",
    "language": "english",
    "country": ["india"],
    "category": ["entertainment"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "8c92e3899d88e5bbd3a6db9787086124",
    "title": "Kani Kusruti exclusive interview: ‘Payal Kapadia really deserved the win at Cannes Film Festival’",
    "link": "https://www.hindustantimes.com/entertainment/others/kani-kusruti-exclusive-interview-all-we-imagine-as-light-cannes-film-festival-101716914901961.html",
    "keywords": ["entertainment"],
    "creator": null,
    "video_url": null,
    "description": "In this exclusive interview, All We Imagine As Light actor Kani Kusruti talked about watching the film at the premiere, and the moment it won the Grand Prix.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:15:25",
    "image_url": "https://www.hindustantimes.com/ht-img/img/2024/05/28/1600x900/cannes_1716915491028_1716920010304.jpg",
    "source_id": "hindustantimes",
    "source_priority": 933,
    "source_url": "http://www.hindustantimes.com",
    "source_icon": "https://i.bytvi.com/domain_icons/hindustantimes.png",
    "language": "english",
    "country": ["india"],
    "category": ["entertainment"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "ffa1f6177beef401e444cb98af1525ba",
    "title": "Desperation led me to 'Biriyaani': Kani Kusruti reveals she had only Rs 3,000 in her bank account",
    "link": "https://www.onmanorama.com/entertainment/entertainment-news/2024/05/29/actor-kani-kusruti-recounts-early-experience-biriyaani-movie-sajin-baabu.html",
    "keywords": null,
    "creator": null,
    "video_url": null,
    "description": "She described how Sajin approached her when she was in a dire financial situation.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:11:47",
    "image_url": "https://img.onmanorama.com/content/dam/mm/en/entertainment/entertainment-news/images/2024/5/29/kani-kusruti.jpg.transform/576x300/image.jpg",
    "source_id": "onmanorama",
    "source_priority": 16247,
    "source_url": "https://www.onmanorama.com",
    "source_icon": "https://i.bytvi.com/domain_icons/onmanorama.png",
    "language": "english",
    "country": ["india"],
    "category": ["entertainment"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  // {
  //   "article_id": "9c4b58b756225e823d7d30e9f9f634f1",
  //   "title": "Hayden Hopkins Expecting Child With MLB Player Joey Gallo, Not Mark Davis",
  //   "link": "https://www.newsr.in/n/Celebrities/1zqvn1ksw1/Hayden-Hopkins-Expecting-Child-With-MLB-Player-Joey.htm",
  //   "keywords": ["celebrities"],
  //   "creator": null,
  //   "video_url": null,
  //   "description":
  //     "The woman rumored to be expecting a child with Las Vegas Raiders owner Mark Davis is actually welcoming a baby with MLB player Joey Gallo, TMZ Sports has learned. The erroneous reports were made over the weekend ... with several irresponsible NFL...Reported by TMZ.com 31 minutes ago.",
  //   "content": "ONLY AVAILABLE IN PAID PLANS",
  //   "pubDate": "2024-05-29 04:10:38",
  //   "image_url": null,
  //   "source_id": "newsr",
  //   "source_priority": 29095901,
  //   "source_url": "https://www.newsr.in",
  //   "source_icon": "https://i.bytvi.com/domain_icons/newsr.png",
  //   "language": "english",
  //   "country": ["india"],
  //   "category": ["entertainment"],
  //   "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
  //   "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  // },
  {
    "article_id": "40bf1aae53da2ecb64f4925a876e2e62",
    "title": 'AEW Denies Tony Khan "Disappointed" At WBD Offer In TV Rights Talks (UPDATED)',
    "link": "https://whatculture.com/wwe/aew-denies-disappointed-at-wbd-offer-in-aew-tv-rights-talks-updated",
    "keywords": ["wwe"],
    "creator": null,
    "video_url": null,
    "description": 'Reporter with close Nick Khan ties cites Tony Khan "disappointment" as AEW TV renewal approaches.',
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:09:08",
    "image_url": "https://cdn4.whatculture.com/images//2023/09/73dd0c6c235ff1c7.jpg",
    "source_id": "whatculture",
    "source_priority": 14143,
    "source_url": "https://whatculture.com",
    "source_icon": "https://i.bytvi.com/domain_icons/whatculture.png",
    "language": "english",
    "country": ["united states of america", "united kingdom", "india"],
    "category": ["entertainment"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "eb47f88cc365d644145521c941a205cd",
    "title": "To Team Heeramandi, A Gratitude Note From Richa Chadha",
    "link": "https://www.news18.com/movies/to-team-heeramandi-a-gratitude-note-from-richa-chadha-8908049.html",
    "keywords": ["movies"],
    "creator": null,
    "video_url": null,
    "description": "In her caption, Richa Chadha reflected on the fun she had on the set despite playing a brief role in the series.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:08:50",
    "image_url": "https://images.news18.com/ibnlive/uploads/2024/05/untitled-design-2024-05-29t093750.350-2024-05-251f4849861cc04907e8cd1227db4c4b-3x2.png",
    "source_id": "news18",
    "source_priority": 6644,
    "source_url": "https://www.news18.com",
    "source_icon": "https://i.bytvi.com/domain_icons/news18.png",
    "language": "english",
    "country": ["india"],
    "category": ["entertainment"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "7bcb8879361d3a5ba1336373c10afb30",
    "title": "Anupam Kher praises Payal Kapadia, Anasuya Sengupta; says 'unknown' Indians are getting 'highest honours' at Cannes now",
    "link": "https://www.hindustantimes.com/entertainment/bollywood/anupam-kher-says-unknown-indians-getting-honoured-at-cannes-now-101716953583069.html",
    "keywords": ["entertainment/bollywood"],
    "creator": null,
    "video_url": null,
    "description": "Anupam Kher lauded Indians who made the country proud at Cannes Film festival 2024. India’s All We Imagine As Light won the prestigious Grand Prix at Cannes.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:08:47",
    "image_url": "https://www.hindustantimes.com/ht-img/img/2024/05/29/1600x900/Anupam_Kher_cannes_2024_1716954246951_1716954247124.jpg",
    "source_id": "hindustantimes",
    "source_priority": 933,
    "source_url": "http://www.hindustantimes.com",
    "source_icon": "https://i.bytvi.com/domain_icons/hindustantimes.png",
    "language": "english",
    "country": ["india"],
    "category": ["entertainment"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "7815c3c86233a7ac26ecbb8c20617c8e",
    "title": "Amitabh Bachchan admits losing track of time on social media, fans react",
    "link": "https://www.mid-day.com/entertainment/bollywood-news/article/amitabh-bachchan-admits-losing-track-of-time-on-social-media-fans-find-it-highly-relatable-23351706",
    "keywords": ["bollywood news"],
    "creator": ["Mid-day"],
    "video_url": null,
    "description": "It looks like Amitabh Bachchan has fallen prey to social media addiction",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:06:07",
    "image_url": "https://images.mid-day.com/images/images/2024/may/bigbscrolling_d.jpg",
    "source_id": "mid_day",
    "source_priority": 4893,
    "source_url": "https://www.mid-day.com",
    "source_icon": "https://i.bytvi.com/domain_icons/mid_day.png",
    "language": "english",
    "country": ["india"],
    "category": ["entertainment"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "d5e8840934045e30c5ceed9bb3efea69",
    "title": "Alia, Kareena to Varun, celebs show solidarity with Palestine",
    "link": "https://www.mid-day.com/entertainment/bollywood-news/article/all-eyes-on-rafah-alia-bhatt-kareena-kapoor-to-varun-dhawan-celebs-join-social-media-protest-to-show-solidarity-with-palestine-23351707",
    "keywords": ["bollywood news"],
    "creator": ["Mid-day"],
    "video_url": null,
    "description": "Alia Bhatt, Kareena Kapoor, Varun Dhawan, Madhuri Dixit, and Samantha Ruth Prabhu have come out to show their solidarity with Palestine",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:06:04",
    "image_url": "https://images.mid-day.com/images/images/2024/may/alleyesonrafahcelebs_d.jpg",
    "source_id": "mid_day",
    "source_priority": 4893,
    "source_url": "https://www.mid-day.com",
    "source_icon": "https://i.bytvi.com/domain_icons/mid_day.png",
    "language": "english",
    "country": ["india"],
    "category": ["entertainment"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
]

export default entertainment
