const entertainment = [
  {
    "article_id": "3ff4d085f859b34a4e82d0d9c05b04f8",
    "title": "Former FTII chief Gajendra Chauhan, whom Payal Kapadia protested against, reacts to her Cannes win: Talent is fine, but...",
    "link": "https://www.dnaindia.com/bollywood/report-former-ftii-chief-gajendra-chauhan-reacts-to-payal-kapadia-s-cannes-win-talent-is-fine-but-3091118",
    "keywords": ["entertainment", "bollywood"],
    "creator": ["Manisha Chauhan"],
    "video_url": null,
    "description": "In 2015, Payal Kapadia and other students protested Gajendra Chauhan's appointment as FTII chairman, believing he lacked the necessary qualifications.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:18:00",
    "image_url": "https://cdn.dnaindia.com/sites/default/files/styles/third/public/2024/05/29/2636093-fotojet-2024-05-29t101453.942-1.jpg",
    "source_id": "dnaindia",
    "source_priority": 18388,
    "source_url": "https://www.dnaindia.com",
    "source_icon": null,
    "language": "english",
    "country": ["india"],
    "category": ["entertainment"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "7660252f5e44268bf2bd041012da713e",
    "title": "KKR On Top Of The World: How Shah Rukh Khan's Team Lit Up Dubai's Burj Khalifa",
    "link": "https://www.ndtv.com/entertainment/kkr-on-top-of-the-world-how-shah-rukh-khans-team-lit-up-dubais-burj-khalifa-5768963#publisher=newsstand",
    "keywords": null,
    "creator": null,
    "video_url": null,
    "description": '"View from the top. It\'s all purple," read the caption on the post',
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:16:26",
    "image_url": "https://c.ndtvimg.com/2024-05/auem9djo_srk_625x300_29_May_24.jpeg",
    "source_id": "ndtv",
    "source_priority": 1204,
    "source_url": "http://www.ndtv.com",
    "source_icon": "https://i.bytvi.com/domain_icons/ndtv.png",
    "language": "english",
    "country": ["india"],
    "category": ["entertainment"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "8c92e3899d88e5bbd3a6db9787086124",
    "title": "Kani Kusruti exclusive interview: ‘Payal Kapadia really deserved the win at Cannes Film Festival’",
    "link": "https://www.hindustantimes.com/entertainment/others/kani-kusruti-exclusive-interview-all-we-imagine-as-light-cannes-film-festival-101716914901961.html",
    "keywords": ["entertainment"],
    "creator": null,
    "video_url": null,
    "description": "In this exclusive interview, All We Imagine As Light actor Kani Kusruti talked about watching the film at the premiere, and the moment it won the Grand Prix.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:15:25",
    "image_url": "https://www.hindustantimes.com/ht-img/img/2024/05/28/1600x900/cannes_1716915491028_1716920010304.jpg",
    "source_id": "hindustantimes",
    "source_priority": 933,
    "source_url": "http://www.hindustantimes.com",
    "source_icon": "https://i.bytvi.com/domain_icons/hindustantimes.png",
    "language": "english",
    "country": ["india"],
    "category": ["entertainment"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "ffa1f6177beef401e444cb98af1525ba",
    "title": "Desperation led me to 'Biriyaani': Kani Kusruti reveals she had only Rs 3,000 in her bank account",
    "link": "https://www.onmanorama.com/entertainment/entertainment-news/2024/05/29/actor-kani-kusruti-recounts-early-experience-biriyaani-movie-sajin-baabu.html",
    "keywords": null,
    "creator": null,
    "video_url": null,
    "description": "She described how Sajin approached her when she was in a dire financial situation.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:11:47",
    "image_url": "https://img.onmanorama.com/content/dam/mm/en/entertainment/entertainment-news/images/2024/5/29/kani-kusruti.jpg.transform/576x300/image.jpg",
    "source_id": "onmanorama",
    "source_priority": 16247,
    "source_url": "https://www.onmanorama.com",
    "source_icon": "https://i.bytvi.com/domain_icons/onmanorama.png",
    "language": "english",
    "country": ["india"],
    "category": ["entertainment"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "9c4b58b756225e823d7d30e9f9f634f1",
    "title": "Hayden Hopkins Expecting Child With MLB Player Joey Gallo, Not Mark Davis",
    "link": "https://www.newsr.in/n/Celebrities/1zqvn1ksw1/Hayden-Hopkins-Expecting-Child-With-MLB-Player-Joey.htm",
    "keywords": ["celebrities"],
    "creator": null,
    "video_url": null,
    "description":
      "The woman rumored to be expecting a child with Las Vegas Raiders owner Mark Davis is actually welcoming a baby with MLB player Joey Gallo, TMZ Sports has learned. The erroneous reports were made over the weekend ... with several irresponsible NFL...Reported by TMZ.com 31 minutes ago.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:10:38",
    "image_url": null,
    "source_id": "newsr",
    "source_priority": 29095901,
    "source_url": "https://www.newsr.in",
    "source_icon": "https://i.bytvi.com/domain_icons/newsr.png",
    "language": "english",
    "country": ["india"],
    "category": ["entertainment"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "40bf1aae53da2ecb64f4925a876e2e62",
    "title": 'AEW Denies Tony Khan "Disappointed" At WBD Offer In TV Rights Talks (UPDATED)',
    "link": "https://whatculture.com/wwe/aew-denies-disappointed-at-wbd-offer-in-aew-tv-rights-talks-updated",
    "keywords": ["wwe"],
    "creator": null,
    "video_url": null,
    "description": 'Reporter with close Nick Khan ties cites Tony Khan "disappointment" as AEW TV renewal approaches.',
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:09:08",
    "image_url": "https://cdn4.whatculture.com/images//2023/09/73dd0c6c235ff1c7.jpg",
    "source_id": "whatculture",
    "source_priority": 14143,
    "source_url": "https://whatculture.com",
    "source_icon": "https://i.bytvi.com/domain_icons/whatculture.png",
    "language": "english",
    "country": ["united states of america", "united kingdom", "india"],
    "category": ["entertainment"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "eb47f88cc365d644145521c941a205cd",
    "title": "To Team Heeramandi, A Gratitude Note From Richa Chadha",
    "link": "https://www.news18.com/movies/to-team-heeramandi-a-gratitude-note-from-richa-chadha-8908049.html",
    "keywords": ["movies"],
    "creator": null,
    "video_url": null,
    "description": "In her caption, Richa Chadha reflected on the fun she had on the set despite playing a brief role in the series.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:08:50",
    "image_url": "https://images.news18.com/ibnlive/uploads/2024/05/untitled-design-2024-05-29t093750.350-2024-05-251f4849861cc04907e8cd1227db4c4b-3x2.png",
    "source_id": "news18",
    "source_priority": 6644,
    "source_url": "https://www.news18.com",
    "source_icon": "https://i.bytvi.com/domain_icons/news18.png",
    "language": "english",
    "country": ["india"],
    "category": ["entertainment"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "7bcb8879361d3a5ba1336373c10afb30",
    "title": "Anupam Kher praises Payal Kapadia, Anasuya Sengupta; says 'unknown' Indians are getting 'highest honours' at Cannes now",
    "link": "https://www.hindustantimes.com/entertainment/bollywood/anupam-kher-says-unknown-indians-getting-honoured-at-cannes-now-101716953583069.html",
    "keywords": ["entertainment/bollywood"],
    "creator": null,
    "video_url": null,
    "description": "Anupam Kher lauded Indians who made the country proud at Cannes Film festival 2024. India’s All We Imagine As Light won the prestigious Grand Prix at Cannes.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:08:47",
    "image_url": "https://www.hindustantimes.com/ht-img/img/2024/05/29/1600x900/Anupam_Kher_cannes_2024_1716954246951_1716954247124.jpg",
    "source_id": "hindustantimes",
    "source_priority": 933,
    "source_url": "http://www.hindustantimes.com",
    "source_icon": "https://i.bytvi.com/domain_icons/hindustantimes.png",
    "language": "english",
    "country": ["india"],
    "category": ["entertainment"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "7815c3c86233a7ac26ecbb8c20617c8e",
    "title": "Amitabh Bachchan admits losing track of time on social media, fans react",
    "link": "https://www.mid-day.com/entertainment/bollywood-news/article/amitabh-bachchan-admits-losing-track-of-time-on-social-media-fans-find-it-highly-relatable-23351706",
    "keywords": ["bollywood news"],
    "creator": ["Mid-day"],
    "video_url": null,
    "description": "It looks like Amitabh Bachchan has fallen prey to social media addiction",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:06:07",
    "image_url": "https://images.mid-day.com/images/images/2024/may/bigbscrolling_d.jpg",
    "source_id": "mid_day",
    "source_priority": 4893,
    "source_url": "https://www.mid-day.com",
    "source_icon": "https://i.bytvi.com/domain_icons/mid_day.png",
    "language": "english",
    "country": ["india"],
    "category": ["entertainment"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "d5e8840934045e30c5ceed9bb3efea69",
    "title": "Alia, Kareena to Varun, celebs show solidarity with Palestine",
    "link": "https://www.mid-day.com/entertainment/bollywood-news/article/all-eyes-on-rafah-alia-bhatt-kareena-kapoor-to-varun-dhawan-celebs-join-social-media-protest-to-show-solidarity-with-palestine-23351707",
    "keywords": ["bollywood news"],
    "creator": ["Mid-day"],
    "video_url": null,
    "description": "Alia Bhatt, Kareena Kapoor, Varun Dhawan, Madhuri Dixit, and Samantha Ruth Prabhu have come out to show their solidarity with Palestine",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 04:06:04",
    "image_url": "https://images.mid-day.com/images/images/2024/may/alleyesonrafahcelebs_d.jpg",
    "source_id": "mid_day",
    "source_priority": 4893,
    "source_url": "https://www.mid-day.com",
    "source_icon": "https://i.bytvi.com/domain_icons/mid_day.png",
    "language": "english",
    "country": ["india"],
    "category": ["entertainment"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
]

export default entertainment;
