const polites = [
  {
    "article_id": "fd9e0f63c8b747a3e0e37c96eff1aa38",
    "title": "Lula removes Brazilian ambassador to Israel amid diplomatic spat",
    "link": "https://www.thehindu.com/news/international/lula-removes-brazilian-ambassador-to-israel-amid-diplomatic-spat/article68230225.ece",
    "keywords": ["world"],
    "creator": null,
    "video_url": null,
    "description": "Israel's move was related to Mr. Lula's remarks likening Israel's war on Gaza to the Holocaust.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 23:07:00",
    "image_url": "https://th-i.thgim.com/public/incoming/pqx04c/article68230227.ece/alternates/LANDSCAPE_1200/2024-05-29T170808Z_523819013_RC2M56A2CN60_RTRMADP_3_ISRAEL-PALESTINIANS-BRAZIL.JPG",
    "source_id": "thehindu",
    "source_priority": 2972,
    "source_url": "https://www.thehindu.com",
    "source_icon": "https://i.bytvi.com/domain_icons/thehindu.png",
    "language": "english",
    "country": ["india"],
    "category": ["politics"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "1f5dd172fa33cdc92cc8f5f6124c1bb8",
    "title": "Starmer's decision over Abbott is part of a wider strategy - but polling suggests trouble ahead",
    "link": "https://www.newsr.in/n/Politics/1zqvn1kz7c/Starmer-decision-over-Abbott-is-part-of.htm",
    "keywords": ["politics"],
    "creator": null,
    "video_url": null,
    "description": "Does Diane Abbott and the row over her future matter?Reported by Sky News 13 minutes ago.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 22:02:48",
    "image_url": null,
    "source_id": "newsr",
    "source_priority": 29095901,
    "source_url": "https://www.newsr.in",
    "source_icon": "https://i.bytvi.com/domain_icons/newsr.png",
    "language": "english",
    "country": ["india"],
    "category": ["politics"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  // {
  //   "article_id": "40464a8fe0052a6fdadd804282573d0c",
  //   "title": "Open access is crucial for self-reliance in science",
  //   "link": "https://www.thehindu.com/opinion/op-ed/open-access-is-crucial-for-self-reliance-in-science/article68228874.ece",
  //   "keywords": ["comment"],
  //   "creator": null,
  //   "video_url": null,
  //   "description": "With the evolving landscape of academic publishing, investing in an all-encompassing subscription model is not prudent",
  //   "content": "ONLY AVAILABLE IN PAID PLANS",
  //   "pubDate": "2024-05-29 20:29:34",
  //   "image_url": "https://www.thehindu.com/theme/images/th-online/1x1_spacer.png",
  //   "source_id": "thehindu",
  //   "source_priority": 2972,
  //   "source_url": "https://www.thehindu.com",
  //   "source_icon": "https://i.bytvi.com/domain_icons/thehindu.png",
  //   "language": "english",
  //   "country": ["india"],
  //   "category": ["politics"],
  //   "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
  //   "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  // },
  // {
  //   "article_id": "f1483f204c11ebdfa855ba5a42b31ef1",
  //   "title": "The BJP cannot bank on ‘asmita’ alone",
  //   "link": "https://www.thehindu.com/opinion/op-ed/the-bjp-cannot-bank-on-asmita-alone/article68228194.ece",
  //   "keywords": ["comment"],
  //   "creator": null,
  //   "video_url": null,
  //   "description": "It has not campaigned on key issues and has also left brand Naveen unscathed",
  //   "content": "ONLY AVAILABLE IN PAID PLANS",
  //   "pubDate": "2024-05-29 20:13:11",
  //   "image_url": "https://th-i.thgim.com/public/incoming/h7vunb/article68228222.ece/alternates/LANDSCAPE_1200/IMG_Naveen_Patnaik_addre_2_1_4VCQ19C1.jpg",
  //   "source_id": "thehindu",
  //   "source_priority": 2972,
  //   "source_url": "https://www.thehindu.com",
  //   "source_icon": "https://i.bytvi.com/domain_icons/thehindu.png",
  //   "language": "english",
  //   "country": ["india"],
  //   "category": ["politics"],
  //   "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
  //   "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  // },
  // {
  //   "article_id": "e7a5102e8bf287b9f4c35ad90032494c",
  //   "title": "20% Lok Sabha candidates face criminal cases in 2024: ADR",
  //   "link": "https://economictimes.indiatimes.com/news/elections/lok-sabha/india/20-lok-sabha-candidates-face-criminal-cases-in-2024-adr/articleshow/110543724.cms",
  //   "keywords": null,
  //   "creator": null,
  //   "video_url": null,
  //   "description": "ADR analysis shows 55% of 2024 Lok Sabha candidates face criminal cases, with 14% facing serious charges, slightly higher than 2019 but still higher than 2009. Average candidate assets have grown 50% since 2019.",
  //   "content": "ONLY AVAILABLE IN PAID PLANS",
  //   "pubDate": "2024-05-29 19:38:25",
  //   "image_url": "https://img.etimg.com/thumb/msid-110543732,width-300,height-225,imgsize-9086,resizemode-75/lok-sabha-election-2024-.jpg",
  //   "source_id": "economictimes_indiatimes",
  //   "source_priority": 376,
  //   "source_url": "https://economictimes.indiatimes.com",
  //   "source_icon": "https://i.bytvi.com/domain_icons/economictimes_indiatimes.png",
  //   "language": "english",
  //   "country": ["india"],
  //   "category": ["politics"],
  //   "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
  //   "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  // },
  {
    "article_id": "ffdeaa3b5278f17c92375490f0a83031",
    "title": "Khadoor Sahib Lok Sabha Polls: Radical Amritpal Singh's kin, supporters keep drug fight narrative going",
    "link": "https://economictimes.indiatimes.com/news/elections/lok-sabha/india/khadoor-sahib-lok-sabha-polls-radical-amritpal-singhs-kin-supporters-keep-drug-fight-narrative-going/articleshow/110543688.cms",
    "keywords": null,
    "creator": null,
    "video_url": null,
    "description":
      "Jailed Sikh preacher Amritpal Singh's entry into the Khadoor Sahib Lok Sabha seat as an Independent candidate, campaigning on a pro-Panth, anti-drug platform, has stirred politics in the region bordering Pakistan. Supporters have placed posters of Sant Jarnail Singh Bhindranwale, highlighting the seat's Panthic sentiment. Amritpal's manifesto focuses on ending the drug culture, releasing prisoners, and ensuring justice in sacrilege cases. While his work against addiction is praised, there are concerns about his pro-Khalistani stance leading to separatism. The contest also includes candidates from SAD (Amritsar), Congress, and BJP, making it a crucial four-cornered contest.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 19:30:10",
    "image_url": "https://img.etimg.com/thumb/msid-110543707,width-300,height-225,imgsize-108624,resizemode-75/radical-amritpals-kin-supporters-keep-drug-fight-narrative-going.jpg",
    "source_id": "economictimes_indiatimes",
    "source_priority": 376,
    "source_url": "https://economictimes.indiatimes.com",
    "source_icon": "https://i.bytvi.com/domain_icons/economictimes_indiatimes.png",
    "language": "english",
    "country": ["india"],
    "category": ["politics"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "fd14bb1e353edf3ab0af8538a3b60f42",
    "title": "Netas join public at home museum of Moosewala amid polls",
    "link": "https://economictimes.indiatimes.com/news/elections/lok-sabha/india/netas-join-public-at-home-museum-of-moosewala-amid-polls/articleshow/110543640.cms",
    "keywords": null,
    "creator": null,
    "video_url": null,
    "description":
      'On the second death anniversary of Punjabi rapper Sidhu Moosewala, fans flock to Moosa village in Mansa district, where he was shot dead. The village has turned into a pilgrimage site, with shops selling merchandise featuring Moosewala. Residents have set up shops to sell his merchandise, which remains in high demand. Moosewala has become a cult figure, and his popularity has surged since his death, with fans considering him a "martyr."',
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 19:19:08",
    "image_url": "https://img.etimg.com/thumb/msid-110543655,width-300,height-225,imgsize-162216,resizemode-75/netas-join-public-at-home-museum-of-moosewala-amid-polls.jpg",
    "source_id": "economictimes_indiatimes",
    "source_priority": 376,
    "source_url": "https://economictimes.indiatimes.com",
    "source_icon": "https://i.bytvi.com/domain_icons/economictimes_indiatimes.png",
    "language": "english",
    "country": ["india"],
    "category": ["politics"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "10b2c41135e92fc09e6ecf565b4fce5c",
    "title": "Congress, SP to blame EVMs for loss: Amit Shah",
    "link": "https://economictimes.indiatimes.com/news/elections/lok-sabha/uttar-pradesh/congress-sp-to-blame-evms-for-loss-amit-shah/articleshow/110543635.cms",
    "keywords": null,
    "creator": null,
    "video_url": null,
    "description":
      "Union Home Minister Amit Shah claimed that the BJP has won 310 seats in the first five phases of the Lok Sabha elections and hopes to cross 400 seats in the sixth and seventh phases. He also predicted that Congress will not cross 40 seats and the SP will struggle to cross even four seats.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 19:18:27",
    "image_url": "https://img.etimg.com/thumb/msid-110543641,width-300,height-225,imgsize-141974,resizemode-75/cong-sp-to-blame-evms-for-loss-shah.jpg",
    "source_id": "economictimes_indiatimes",
    "source_priority": 376,
    "source_url": "https://economictimes.indiatimes.com",
    "source_icon": "https://i.bytvi.com/domain_icons/economictimes_indiatimes.png",
    "language": "english",
    "country": ["india"],
    "category": ["politics"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "7090abceca84e8e137ad94caeec876d2",
    "title": "BJP banks on ex-PM's legacy, son's influence in battle of Ballia",
    "link": "https://economictimes.indiatimes.com/news/elections/lok-sabha/uttar-pradesh/bjp-banks-on-ex-pms-legacy-sons-influence-in-battle-of-ballia/articleshow/110543584.cms",
    "keywords": null,
    "creator": null,
    "video_url": null,
    "description":
      "Former PM Chandra Shekhar's son Neeraj Shekhar is contesting the BJP's seat in Ballia for the first time, balancing his father's socialist roots with his party's nationalist leanings. Shekhar was elected to the Lok Sabha for eight terms from Ballia in 1977. The BJP has maintained relations with followers of Chandra Shekhar, who are considered extra votes for the party.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 19:12:28",
    "image_url": "https://img.etimg.com/thumb/msid-110543610,width-300,height-225,imgsize-34934,resizemode-75/ls-polls-2024-bjp-releases-10th-list-of-candidates-fields-ex-pm-chandra-shekhars-son-neeraj-from-ballia-ss-ahluwalia-from-asansol.jpg",
    "source_id": "economictimes_indiatimes",
    "source_priority": 376,
    "source_url": "https://economictimes.indiatimes.com",
    "source_icon": "https://i.bytvi.com/domain_icons/economictimes_indiatimes.png",
    "language": "english",
    "country": ["india"],
    "category": ["politics"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "5b233a995fde4b6b6e6a48ad2aafbdee",
    "title": "Battle of Jadavpur: TMC nominee counts on knowing 'pulse of people' in Triangular contest",
    "link": "https://economictimes.indiatimes.com/news/elections/lok-sabha/west-bengal/battle-of-jadavpur-tmc-nominee-counts-on-knowing-pulse-of-people-in-triangular-contest/articleshow/110543517.cms",
    "keywords": null,
    "creator": null,
    "video_url": null,
    "description":
      "Jadavpur Lok Sabha seat in West Bengal is set to face a three-cornered fight between CPI-M's youth face Srijan Bhattacharya, Trinamool Youth wing president Saayoni Ghosh, and BJP's Anirban Ganguly. The constituency, which is mostly located in the South 24 Parganas district, is predominantly rural and semi-urban. Trinamool candidate Ghosh is confident of winning, citing her extensive travel and understanding of the people's pulse.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 19:05:04",
    "image_url": "https://img.etimg.com/thumb/msid-110543550,width-300,height-225,imgsize-197542,resizemode-75/jadavpur-may-09-ani-trinamool-congress-candidate-from-jadavpur-sayani-ghosh-.jpg",
    "source_id": "economictimes_indiatimes",
    "source_priority": 376,
    "source_url": "https://economictimes.indiatimes.com",
    "source_icon": "https://i.bytvi.com/domain_icons/economictimes_indiatimes.png",
    "language": "english",
    "country": ["india"],
    "category": ["politics"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "c06703d9680a11d786cbd99dda981136",
    "title": "‘Rishi Rich’ has been a victim of success shaming",
    "link": "https://www.firstpost.com/opinion/rishi-rich-has-been-a-victim-of-success-shaming-13776273.html",
    "keywords": ["opinion"],
    "creator": ["Firstpost"],
    "video_url": null,
    "description": "As a self-made man, Rishi Sunak has borne the brunt of media and social media prejudice",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 03:21:14",
    "image_url": "https://images.firstpost.com/uploads/2024/05/RishiSunak1200AP-2024-05-0c2cd85d1b83d6f83528c2856782b53a.jpg",
    "source_id": "firstpost",
    "source_priority": 5906,
    "source_url": "https://www.firstpost.com",
    "source_icon": "https://i.bytvi.com/domain_icons/firstpost.png",
    "language": "english",
    "country": ["india"],
    "category": ["politics"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "5d87761ccc3bfa8fd5705d43b4bf5419",
    "title": "Post-poll violence: Tea stalls in Odisha's Ganjam asked to close by 8.30 pm",
    "link": "https://economictimes.indiatimes.com/news/elections/lok-sabha/india/post-poll-violence-tea-stalls-in-odishas-ganjam-asked-to-close-by-8-30-pm/articleshow/110518269.cms",
    "keywords": null,
    "creator": null,
    "video_url": null,
    "description": "Police in Ganjam district, Odisha, have ordered tea stall and dhaba owners to close by 8.30 pm until June 4 to prevent post-poll violence.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 03:08:02",
    "image_url": "https://img.etimg.com/thumb/msid-110518327,width-300,height-225,imgsize-23230,resizemode-75/odisha-khordha-police-conduct-flag-march-in-wake-of-pre-poll-violence-in-ganjam.jpg",
    "source_id": "economictimes_indiatimes",
    "source_priority": 376,
    "source_url": "https://economictimes.indiatimes.com",
    "source_icon": "https://i.bytvi.com/domain_icons/economictimes_indiatimes.png",
    "language": "english",
    "country": ["india"],
    "category": ["politics"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "5b46a861bab395eb51be8da843bf8242",
    "title": "PM Modi Exclusive: 'Don't Have Cordial Relations, But I Call Them When...': NaMo On Ties With Gandhis",
    "link": "https://news.abplive.com/elections/pm-modi-exclusive-interview-dont-have-cordial-relations-but-i-call-them-namo-on-ties-with-gandhis-1690958",
    "keywords": ["election 2024"],
    "creator": ["ABP News Bureau"],
    "video_url": null,
    "description":
      "In the run up to the seventh and final phase of the 2024 Lok Sabha elections, Prime Minister Narendra Modi spoke with ABP Network in an exclusive interview. Speaking with Suman De of ABP Ananda and Rohit Sawal and Romana Isar Khan of ABP News, PM Modi revealed how his personal relations with the other political parties are like. He also recounted how he personally called his political rival Rahul Gandhi when his helicopter faced issues and even sent help for Sonia Gandhi.Know Why PM Modi Spoke With Rahul Gandhi PersonallyPM Modi told ABP News during the exclusive interview, how he does not have cordial relations with the Gandhi family but stands with them in times of trouble.Recalling an incident from the 2019 Lok Sabha elections, PM Modi said: \"I have good relationship with everyone except the royal family. I have no personal relationship with the royal family, but I have always been there for them in times of trouble. During some election, there was an issue with Rahul Gandhi's airplane in Maharashtra, and I immediately called him.\"Once, while Sonia Gandhi was campaigning against me in Kashi, she suddenly fell ill. I immediately arranged for a special plane to bring her to Delhi,\" he added.Watch | नरेंद्र मोदी ने जब राहुल गांधी-सोनिया गांधी को किया था फोन...PM @narendramodi ने सुनाया किस्सा @SavalRohit | @romanaisarkhan | @IamSumanDe#PMModiOnABP #NarendraModi #PMModi #Rahulgandhi #soniagandhi #LokSabhaElection2024 #ModiInterview #News #Hindi #Hindinews… pic.twitter.com/Iksr7Cy9sb— ABP News (@ABPNews) May 28, 2024PM Modi Recalls When Sonia Gandhi's Helicopter Met With An Accident In DamanPM Modi also recounted an incident when Sonia Gandhi's helicopter crashed in Daman, with Ahmed Patel on board.Stating that he was the Chief Minister of Gujarat at that time this incident occured, PM Modi said: \"I spoke to Ahmed Patel and told him that the situation is very serious, and I immediately arranged for an air ambulance. He informed me that they were safe, but the helicopter was significantly damaged. I believe that these are all people working for our country. This is a sense of kinship, and I don't mix politics with it.\"#PMModiOnABP | PM मोदी ने राहुल गांधी को फोन क्यों किया? देखिए पीएम (@narendramodi) ने इंटरव्यू में खुद किया खुलासा @SavalRohit | @romanaisarkhan | @IamSumanDehttps://t.co/smwhXURgtc#PMModi #NarendraModi #LokSabhaElections #Elections2024 #NarendraBhaiOnABP #RahulGandhi… pic.twitter.com/J4qIctcsOE— ABP News (@ABPNews) May 28, 2024ALSO READ: PM Modi Interview: An 'Ekta Mall' In Every State Capital — PM Modi Shares His 'Unity' Concept",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 02:53:23",
    "image_url": "https://feeds.abplive.com/onecms/images/uploaded-images/2024/05/29/6cc1a9d8c81e7819ad49f8867714425b1716950204167927_original.png",
    "source_id": "abplive",
    "source_priority": 10959,
    "source_url": "http://abplive.com",
    "source_icon": "https://i.bytvi.com/domain_icons/abplive.jpg",
    "language": "english",
    "country": ["india"],
    "category": ["politics"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "4b694a09e65f8764d554ac14795e6f5b",
    "title": "Mani Shankar Aiyar Sparks Fresh Row, Says Chinese 'Allegedly Invaded' India in 1962, Apologises for 'Mistake'",
    "link": "https://www.news18.com/politics/mani-shankar-aiyar-chinese-allegedly-invaded-india-1962-row-apologises-later-8907991.html",
    "keywords": ["politics"],
    "creator": null,
    "video_url": null,
    "description": 'Both the Congress and BJP reacted to his controversial remarks with the former saying it has distanced itself from the "original phraseology" and the latter calling it a "brazen attempt at revisionism"',
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 02:38:15",
    "image_url": "https://images.news18.com/ibnlive/uploads/2024/01/congress-leader-mani-shankar-aiyar-1-2024-01-714e2e27b922a61199d9eb2d29a94ae2-3x2.jpg",
    "source_id": "news18",
    "source_priority": 6644,
    "source_url": "https://www.news18.com",
    "source_icon": "https://i.bytvi.com/domain_icons/news18.png",
    "language": "english",
    "country": ["india"],
    "category": ["politics"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "c5cddf1bf445a171dfbfe76fbe3941b8",
    "title": "Lok Sabha Elections 2024 Live: Ahead Of Phase 7, PM Modi To Address Poll Rallies In Bengal, Odisha Today",
    "link": "https://news.abplive.com/elections/lok-sabha-elections-2024-live-updates-may-29-pm-modi-akhilesh-yadav-rahul-gandhi-priyanka-sonia-mamata-banerjee-arvind-kejriwal-amit-shah-election-commission-of-india-1690945",
    "keywords": ["election 2024"],
    "creator": ["ABP News Bureau"],
    "video_url": null,
    "description":
      'Lok Sabha Elections 2024 Live: Hello and welcome to this Live Blog. Please follow this space and keep refreshing the page for all the latest updates and developments on Lok Sabha elections.Rahul Gandhi Says Narendra Modi Will Not Be PM After June 4Rahul Gandhi, the Congress leader, stated on Tuesday that Narendra Modi will not be the next prime minister, calling it a "guarantee". Addressing a rally in Modi\'s parliamentary constituency of Varanasi, Gandhi stated that the contest here was not between a prime ministerial candidate and Congress nominee Ajay Rai because Modi will not return as PM."I am telling you with a guarantee that after June 4, Narendra Modi ji will not be the prime minister of this country," Gandhi stated. "The contest between the two is intense and in this contest, Ajay Rai may win," he stated.The fight is between Varanasi autorickshaw drivers, Banarasi saree weavers, farmers, labourers, and billionaires.Gandhi claimed: Modi has waived billionaires\' loans totalling Rs 16 lakh crore.Karnataka, Telangana & Himachal Results Will Repeat For BJP In Odisha: PatnaikHours after Union Home Minister Amit Shah claimed that Naveen Patnaik would become a former chief minister after the vote count on June 4, the ruling BJD president said on Tuesday that the saffron party will face the same electoral fate as in Karnataka, Telangana, and Himachal Pradesh.Patnaik stated in a video message that the Bhartiya Janata Party promised to form a government in Karnataka but failed to do so. They made the same claim for Telangana and failed. They made the same claim in Himachal Pradesh and failed as well." "I am certain that their same reputation will continue in this elections in Odisha," said Patnaik, Odisha\'s five-time chief minister.Earlier, Shah claimed at three consecutive election rallies that Patnaik would become a former chief minister after the votes were counted on June 4, and the BJP is poised to form the government in Odisha after winning more than 75 of the state\'s 147 seats. Shah also claimed that the saffron party candidates would win 17 of the state\'s 21 Lok Sabha seats.PM Modi To Meditate At Vivekananda\'s Landmark In Tamil Nadu After Poll Campaign Ends On May 30Following the conclusion of the Lok Sabha election campaign on May 30, Prime Minister Narendra Modi will meditate at the Rock Memorial, a monument dedicated to Swami Vivekananda in Kanyakumari, according to BJP leaders on Tuesday.The Tamil Nadu unit of the Congress stated that the Election Commission should not grant permission for the PM\'s programme because the model code of conduct was in effect. TNCC chief K Selvaperunthagai claimed that such a move was an attempt at "indirect campaigning" after the vote canvassing had concluded.The Prime Minister will meditate at Dhyan Mandapam from the evening of May 30 to the evening of June 1 where Vivekananda, a spiritual icon admired by Modi, is said to have had a divine vision about \'Bharat Mata\', according to BJP leaders. Following the 2019 election campaign, the prime minister conducted a similar meditation exercise in a Kedarnath cave.',
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 01:57:52",
    "image_url": "https://feeds.abplive.com/onecms/images/uploaded-images/2024/05/28/871aecf193ea64f7c8dd1214f0c21f271716919608559556_original.jpg",
    "source_id": "abplive",
    "source_priority": 10959,
    "source_url": "http://abplive.com",
    "source_icon": "https://i.bytvi.com/domain_icons/abplive.jpg",
    "language": "english",
    "country": ["india"],
    "category": ["politics"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "612419b452ae7c867778f7371036d799",
    "title": "Lok Sabha Election 2024 LIVE: PM Modi to hold rally in Bengal's Diamond Harbour, roadshow in Kolkata",
    "link": "https://www.hindustantimes.com/india-news/lok-sabha-election-2024-live-updates-bjp-congress-india-pm-narendra-modi-rahul-gandhi-latest-news-may-29-101716944009872.html",
    "keywords": ["elections"],
    "creator": null,
    "video_url": null,
    "description": "Lok Sabha Election 2024 LIVE: Check out all the latest news and live updates from 2024 general election in India here.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 01:51:58",
    "image_url": "https://www.hindustantimes.com/ht-img/img/2024/05/29/1600x900/Prime-Minister-Narendra-Modi-in-Jadavpur-on-Tuesda_1716945647414_1716945670617.jpg",
    "source_id": "hindustantimes",
    "source_priority": 933,
    "source_url": "http://www.hindustantimes.com",
    "source_icon": "https://i.bytvi.com/domain_icons/hindustantimes.png",
    "language": "english",
    "country": ["india"],
    "category": ["politics"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "4344923310fe411881bbcf6b4a161472",
    "title": "Lok Sabha Elections 2024: PM Modi to meditate at Vivekananda Rock Memorial after high-octane campaign ends tomorrow",
    "link": "https://www.livemint.com/elections/lok-sabha-elections-2024-pm-modi-to-madidate-vivekananda-rock-memorial-after-high-octane-campaign-ends-tomorrow-11716945144095.html",
    "keywords": null,
    "creator": null,
    "video_url": null,
    "description": "Lok Sabha Elections: The Prime Minister, the biggest star campaigner of the ruling BJP, will arrive at the memorial off the coast of Kanyakumari on May 30 and may leave for Delhi on June 1, the last day of the polling.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-29 01:45:08",
    "image_url": "https://www.livemint.com/lm-img/img/2024/05/29/1600x900/ANI-20240514058-0_1716619217687_1716946026148.jpg",
    "source_id": "livemint",
    "source_priority": 7134,
    "source_url": "https://www.livemint.com",
    "source_icon": "https://i.bytvi.com/domain_icons/livemint.png",
    "language": "english",
    "country": ["india"],
    "category": ["politics"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    "article_id": "e23723eb78bc0379c15501ea0b401b85",
    "title": "U.S. must improve nuclear weapons or face threats from China, Russia",
    "link": "https://www.washingtontimes.com/news/2024/may/28/us-must-improve-nuclear-weapons-or-face-threats-fr/?utm_source=RSS_Feed&utm_medium=RSS",
    "keywords": null,
    "creator": ["David Jonas and Patrick Rhoads"],
    "video_url": null,
    "description": "Our nuclear weapons capability is highly compromised and in need of immediate attention, according to a report issued last October by the Strategic Nuclear Posture Committee.",
    "content": "ONLY AVAILABLE IN PAID PLANS",
    "pubDate": "2024-05-28 22:28:19",
    "image_url": "https://twt-thumbs.washtimes.com/media/image/2024/05/28/B4_Jonas1_s859x929.jpg?b57be3d1e841b0ca0fce3b954e3a5b1bd07aef7f",
    "source_id": "washingtontimes",
    "source_priority": 9784,
    "source_url": "https://www.washingtontimes.com",
    "source_icon": null,
    "language": "english",
    "country": ["india"],
    "category": ["politics"],
    "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
    "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  // {
  //   "article_id": "be6e73605bbc446835c65248f4de65fe",
  //   "title": "The skunk at Fed Chairman Powell's tea party",
  //   "link": "https://www.washingtontimes.com/news/2024/may/28/skunk-at-fed-chairman-powells-tea-party/?utm_source=RSS_Feed&utm_medium=RSS",
  //   "keywords": null,
  //   "creator": ["Peter Morici"],
  //   "video_url": null,
  //   "description": "News that inflation eased in April inspired euphoria in securities markets.",
  //   "content": "ONLY AVAILABLE IN PAID PLANS",
  //   "pubDate": "2024-05-28 22:24:52",
  //   "image_url": "https://twt-thumbs.washtimes.com/media/image/2024/05/28/B4_Morici1_s953x929.jpg?2d66b21cb0aa46b9c448f1d99a970e3a914ba85a",
  //   "source_id": "washingtontimes",
  //   "source_priority": 9784,
  //   "source_url": "https://www.washingtontimes.com",
  //   "source_icon": null,
  //   "language": "english",
  //   "country": ["india"],
  //   "category": ["politics"],
  //   "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
  //   "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  // },
  // {
  //   "article_id": "b20be986dfecfe395e803baaad92befc",
  //   "title": "Pittsburgh or Paris? Let's put American energy first",
  //   "link": "https://www.washingtontimes.com/news/2024/may/28/pittsburgh-or-paris-lets-put-american-energy-first/?utm_source=RSS_Feed&utm_medium=RSS",
  //   "keywords": null,
  //   "creator": ["Carla Sands"],
  //   "video_url": null,
  //   "description": "The Paris Agreement is a bad deal for America.",
  //   "content": "ONLY AVAILABLE IN PAID PLANS",
  //   "pubDate": "2024-05-28 22:21:15",
  //   "image_url": "https://twt-thumbs.washtimes.com/media/image/2024/05/28/B1sandsLGparisclimate_s743x929.jpg?ffb8d13c7a049f99118b23b64d048f07c00a05d5",
  //   "source_id": "washingtontimes",
  //   "source_priority": 9784,
  //   "source_url": "https://www.washingtontimes.com",
  //   "source_icon": null,
  //   "language": "english",
  //   "country": ["india"],
  //   "category": ["politics"],
  //   "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
  //   "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
  //   "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
  // },
]

export default polites
